#!/bin/sh
set -eu

rootfs=$1
hostname_value=$2
shift 2
tools=$rootfs/.nvx-agent

mount --make-rprivate /
mount --bind "$rootfs" "$rootfs"
rm -rf "$tools"
mkdir -p \
    "$tools" \
    "$rootfs/dev/pts" \
    "$rootfs/dev/shm" \
    "$rootfs/.oldroot" \
    "$rootfs/proc" \
    "$rootfs/sys"
mount -t tmpfs -o mode=755,nosuid,nodev tmpfs "$tools"
cp /bin/busybox.static "$tools/busybox"
chmod 0555 "$tools/busybox"
mount -o remount,ro,nosuid,nodev "$tools"
mount -t proc -o nosuid,nodev,noexec proc "$rootfs/proc"
mount -t sysfs -o ro,nosuid,nodev,noexec sysfs "$rootfs/sys"
mount -t tmpfs -o mode=755,nosuid tmpfs "$rootfs/dev"
mkdir -p "$rootfs/dev/pts" "$rootfs/dev/shm"
mount -t devpts -o newinstance,ptmxmode=0666,mode=0620 devpts "$rootfs/dev/pts"
mount -t tmpfs -o mode=1777,nosuid,nodev tmpfs "$rootfs/dev/shm"

mknod -m 666 "$rootfs/dev/null" c 1 3
mknod -m 666 "$rootfs/dev/zero" c 1 5
mknod -m 666 "$rootfs/dev/full" c 1 7
mknod -m 666 "$rootfs/dev/random" c 1 8
mknod -m 666 "$rootfs/dev/urandom" c 1 9
mknod -m 666 "$rootfs/dev/tty" c 5 0
ln -s pts/ptmx "$rootfs/dev/ptmx"
ln -s /proc/self/fd "$rootfs/dev/fd"
ln -s /proc/self/fd/0 "$rootfs/dev/stdin"
ln -s /proc/self/fd/1 "$rootfs/dev/stdout"
ln -s /proc/self/fd/2 "$rootfs/dev/stderr"

hostname "$hostname_value"
cd "$rootfs"
pivot_root . .oldroot
/.oldroot/bin/busybox umount -l /.oldroot
exec /.nvx-agent/busybox setpriv \
    --reuid 0 \
    --regid 0 \
    --clear-groups \
    --no-new-privs \
    --bounding-set=-all \
    --inh-caps=-all \
    --ambient-caps=-all \
    "$@"
